FROM docker.io/rust:slim-bullseye AS builder

RUN apt update && \
    apt install -y \
      pkg-config \
      libssl-dev \
      gcc \
      g++

WORKDIR /usr/src/rust-tekton-nodes
COPY . .
RUN cargo install --path .

FROM docker.io/debian:bullseye-slim AS runner
RUN apt update && \
    apt install -y \
      libssl-dev
COPY --from=builder /usr/local/cargo/bin/file-server /usr/local/bin/file-server
CMD ["file-server"]